// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9e7WDE5tau7paYnoF57mAZDZVf77oqsU',
    appId: '1:569671663150:web:2dcd448cc1f182d35069bf',
    messagingSenderId: '569671663150',
    projectId: 'team-dijkstra',
    authDomain: 'team-dijkstra.firebaseapp.com',
    storageBucket: 'team-dijkstra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3lCYyq69QN4hDMAWOV6C0oAOoVh-ITU',
    appId: '1:569671663150:android:5b603819a8fcb8305069bf',
    messagingSenderId: '569671663150',
    projectId: 'team-dijkstra',
    storageBucket: 'team-dijkstra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEH9Kd91wwykkPZgMMPtjbQ-Brk9eqbmQ',
    appId: '1:569671663150:ios:36a49b0399c7d0495069bf',
    messagingSenderId: '569671663150',
    projectId: 'team-dijkstra',
    storageBucket: 'team-dijkstra.appspot.com',
    iosClientId: '569671663150-hd0l0rvkjoqvkold4rtkbek0rt8vuf7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessFlutter',
  );
}
